SELECT * FROM WEB001Xb WHERE COMX_ID = 17

SELECT * FROM WEBX_AUX1
--DELETE FROM WEBX_AUX1

SELECT * FROM WEB002X


SELECT * FROM WEB001X WHERE COMX_ID IN (5,17)
SELECT * FROM WEB001XF WHERE COMX_ID IN (5,17)

SELECT 
A.[WEB0_MOM],
A.[WEB0_USR],
A.[COMX_ID],
A.[WEB0_NRO_C],
B.WEB2_DES,
A.[WEB0_VERS],
A.[WEB0_OBS]
FROM WEB000X A
JOIN WEB002X B ON B.WEB2_ID = A.WEB2_ID
WHERE COMX_ID IN (5,17) AND WEB0_TIP = 'A'