SELECT
C.COMX_SDE AS SECCION,COUNT(*) AS CANT_PUBLICADAS
FROM WEB000X_AUX A
JOIN WEB001Xc B ON B.COMX_ID = A.COMX_ID
JOIN WEB003X C ON C.COMX_COD = B.COMX_COD
WHERE WEB2_ID = 4
GROUP BY A.COMX_COD,C.COMX_SDE
ORDER BY COUNT(*) DESC

SELECT
A.WEB0_FEC AS FEC_PUBLICACION,COUNT(*) AS CANT_PUBLICACIONES
FROM WEB000X_AUX A
WHERE WEB2_ID = 4
GROUP BY A.WEB0_FEC
ORDER BY A.WEB0_FEC

SELECT
B.COMX_AUT AS AUTOR,COUNT(*) AS CANT_PUBLICACIONES
FROM WEB000X A
JOIN WEB001X B ON B.COMX_ID = A.COMX_ID
WHERE WEB2_ID = 4
GROUP BY B.COMX_AUT
ORDER BY COUNT(*) DESC

SELECT
B.COMX_REV AS REVISOR,COUNT(*) AS CANT_PUBLICACIONES
FROM WEB000X A
JOIN WEB001X B ON B.COMX_ID = A.COMX_ID
WHERE WEB2_ID = 4
GROUP BY B.COMX_REV
ORDER BY COUNT(*) DESC