gx.evt.autoSkip=false;function tseg002(){this.ServerClass="TSEG002";this.PackageName="GeneXus.Programs";this.setObjectType("trn");this.hasEnterEvent=true;this.SetStandaloneVars=function(){this.AV7USUCOD=gx.fn.getControlValue("vUSUCOD");this.Gx_mode=gx.fn.getControlValue("vMODE");this.AV9SISTEMA=gx.fn.getControlValue("vSISTEMA");this.AV8USUARIO=gx.fn.getControlValue("vUSUARIO")};this.Valid_Usu_cod=function(){try{var a=gx.util.balloon.getNew("USU_COD");this.AnyError=0;if(gx.text.trim(this.A6USU_COD)==""){try{a.setError("DEBE CARGAR UN CÓDIGO DE USUARIO.");
this.AnyError=1}catch(b){}}}catch(b){}try{if(a==null){return true}return a.show()}catch(b){}return true};this.Valid_Usu_des=function(){try{var a=gx.util.balloon.getNew("USU_DES");this.AnyError=0;if(gx.text.trim(this.A7USU_DES)==""){try{a.setError("DEBE CARGAR UNA DESCRIPCIÓN DE USUARIO.");this.AnyError=1}catch(b){}}}catch(b){}try{if(a==null){return true}return a.show()}catch(b){}return true};this.Valid_Usu_cla=function(){try{var a=gx.util.balloon.getNew("USU_CLA");this.AnyError=0;if(gx.text.trim(this.A155USU_CLA)==""){try{a.setError("DEBE INGRESAR UNA CONTRASEÑA.");
this.AnyError=1}catch(b){}}}catch(b){}try{if(a==null){return true}return a.show()}catch(b){}return true};this.e120f2_client=function(){this.executeServerEvent("AFTER TRN",true)};this.e130f15_client=function(){this.executeServerEvent("ENTER",true)};this.e140f15_client=function(){this.executeServerEvent("CANCEL",true)};this.GXValidFnc=[];this.GXCtrlIds=[2,5,8,9,15,20,25,30,35,40];this.GXLastCtrlId=40;this.GXValidFnc[2]={fld:"TABLEMAIN",grid:0};this.GXValidFnc[5]={fld:"TABLETOOLBAR",grid:0};this.GXValidFnc[8]={fld:"GROUPDATA",grid:0};
this.GXValidFnc[9]={fld:"TABLE1",grid:0};this.GXValidFnc[15]={fld:"TABLE2",grid:0};this.GXValidFnc[18]={fld:"TEXTBLOCKUSU_COD",format:0,grid:0};this.GXValidFnc[20]={lvl:0,type:"char",len:16,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Usu_cod,isvalid:null,fld:"USU_COD",gxz:"Z6USU_COD",gxold:"O6USU_COD",gxvar:"A6USU_COD",ucs:[],op:[20],ip:[20],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A6USU_COD=a},v2z:function(a){gx.O.Z6USU_COD=a},v2c:function(){gx.fn.setControlValue("USU_COD",gx.O.A6USU_COD,0)
},c2v:function(){gx.O.A6USU_COD=this.val()},val:function(){return gx.fn.getControlValue("USU_COD")},nac:function(){return this.Gx_mode!="INS"}};this.GXValidFnc[23]={fld:"TEXTBLOCKUSU_DES",format:0,grid:0};this.GXValidFnc[25]={lvl:0,type:"char",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Usu_des,isvalid:null,fld:"USU_DES",gxz:"Z7USU_DES",gxold:"O7USU_DES",gxvar:"A7USU_DES",ucs:[],op:[25],ip:[25],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A7USU_DES=a},v2z:function(a){gx.O.Z7USU_DES=a
},v2c:function(){gx.fn.setControlValue("USU_DES",gx.O.A7USU_DES,0)},c2v:function(){gx.O.A7USU_DES=this.val()},val:function(){return gx.fn.getControlValue("USU_DES")},nac:function(){return false}};this.GXValidFnc[28]={fld:"TEXTBLOCKUSU_CLA",format:0,grid:0};this.GXValidFnc[30]={lvl:0,type:"char",len:20,dec:0,sign:false,isPwd:true,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Usu_cla,isvalid:null,fld:"USU_CLA",gxz:"Z155USU_CLA",gxold:"O155USU_CLA",gxvar:"A155USU_CLA",ucs:[],op:[30],ip:[30],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A155USU_CLA=a
},v2z:function(a){gx.O.Z155USU_CLA=a},v2c:function(){gx.fn.setControlValue("USU_CLA",gx.O.A155USU_CLA,0)},c2v:function(){gx.O.A155USU_CLA=this.val()},val:function(){return gx.fn.getControlValue("USU_CLA")},nac:function(){return false}};this.GXValidFnc[33]={fld:"TEXTBLOCKUSU_INT",format:0,grid:0};this.GXValidFnc[35]={lvl:0,type:"char",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"USU_INT",gxz:"Z180USU_INT",gxold:"O180USU_INT",gxvar:"A180USU_INT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A180USU_INT=a
},v2z:function(a){gx.O.Z180USU_INT=a},v2c:function(){gx.fn.setControlValue("USU_INT",gx.O.A180USU_INT,0)},c2v:function(){gx.O.A180USU_INT=this.val()},val:function(){return gx.fn.getControlValue("USU_INT")},nac:function(){return false}};this.GXValidFnc[38]={fld:"TEXTBLOCKUSU_MAIW",format:0,grid:0};this.GXValidFnc[40]={lvl:0,type:"svchar",len:256,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"USU_MAIW",gxz:"Z249USU_MAIW",gxold:"O249USU_MAIW",gxvar:"A249USU_MAIW",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A249USU_MAIW=a
},v2z:function(a){gx.O.Z249USU_MAIW=a},v2c:function(){gx.fn.setControlValue("USU_MAIW",gx.O.A249USU_MAIW,0)},c2v:function(){gx.O.A249USU_MAIW=this.val()},val:function(){return gx.fn.getControlValue("USU_MAIW")},nac:function(){return false}};this.A6USU_COD="";this.Z6USU_COD="";this.O6USU_COD="";this.A7USU_DES="";this.Z7USU_DES="";this.O7USU_DES="";this.A155USU_CLA="";this.Z155USU_CLA="";this.O155USU_CLA="";this.A180USU_INT="";this.Z180USU_INT="";this.O180USU_INT="";this.A249USU_MAIW="";this.Z249USU_MAIW="";
this.O249USU_MAIW="";this.AV11Context={};this.AV7USUCOD="";this.AV9SISTEMA="";this.AV8USUARIO="";this.Gx_mode="";this.ServerEvents=["e120f2_client","e130f15_client","e140f15_client"];this.EnterCtrl=["BTN_ENTER"];this.VarControlMap.AV7USUCOD={id:"vUSUCOD",grid:0,type:"char"};this.VarControlMap.Gx_mode={id:"vMODE",grid:0,type:"char"};this.VarControlMap.AV9SISTEMA={id:"vSISTEMA",grid:0,type:"char"};this.VarControlMap.AV8USUARIO={id:"vUSUARIO",grid:0,type:"char"};this.SetStandaloneVars()}tseg002.prototype=new gx.GxObject;
gx.setParentObj(new tseg002());